/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppBoqRouteImport } from './routes/_app/boq'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppFindingsRouteImport } from './routes/_app/findings'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppNewAuditRouteImport } from './routes/_app/new-audit'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppProcessingRouteImport } from './routes/_app/processing'
import { Route as AppReportRouteImport } from './routes/_app/report'
import { Route as AppResultsRouteImport } from './routes/_app/results'
import { Route as AppRevisionsRouteImport } from './routes/_app/revisions'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBoqRoute = AppBoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppFindingsRoute = AppFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppNewAuditRoute = AppNewAuditRouteImport.update({
  id: '/new-audit',
  path: '/new-audit',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppProcessingRoute = AppProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppRevisionsRoute = AppRevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boq': typeof AppBoqRoute
  '/documents': typeof AppDocumentsRoute
  '/findings': typeof AppFindingsRoute
  '/history': typeof AppHistoryRoute
  '/new-audit': typeof AppNewAuditRoute
  '/overview': typeof AppOverviewRoute
  '/processing': typeof AppProcessingRoute
  '/report': typeof AppReportRoute
  '/results': typeof AppResultsRoute
  '/revisions': typeof AppRevisionsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boq': typeof AppBoqRoute
  '/documents': typeof AppDocumentsRoute
  '/findings': typeof AppFindingsRoute
  '/history': typeof AppHistoryRoute
  '/new-audit': typeof AppNewAuditRoute
  '/overview': typeof AppOverviewRoute
  '/processing': typeof AppProcessingRoute
  '/report': typeof AppReportRoute
  '/results': typeof AppResultsRoute
  '/revisions': typeof AppRevisionsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/boq': typeof AppBoqRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/findings': typeof AppFindingsRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/new-audit': typeof AppNewAuditRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/processing': typeof AppProcessingRoute
  '/_app/report': typeof AppReportRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/revisions': typeof AppRevisionsRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boq'
    | '/documents'
    | '/findings'
    | '/history'
    | '/new-audit'
    | '/overview'
    | '/processing'
    | '/report'
    | '/results'
    | '/revisions'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boq'
    | '/documents'
    | '/findings'
    | '/history'
    | '/new-audit'
    | '/overview'
    | '/processing'
    | '/report'
    | '/results'
    | '/revisions'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/boq'
    | '/_app/documents'
    | '/_app/findings'
    | '/_app/history'
    | '/_app/new-audit'
    | '/_app/overview'
    | '/_app/processing'
    | '/_app/report'
    | '/_app/results'
    | '/_app/revisions'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/boq': {
      id: '/_app/boq'
      path: '/boq'
      fullPath: '/boq'
      preLoaderRoute: typeof AppBoqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/findings': {
      id: '/_app/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof AppFindingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new-audit': {
      id: '/_app/new-audit'
      path: '/new-audit'
      fullPath: '/new-audit'
      preLoaderRoute: typeof AppNewAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/processing': {
      id: '/_app/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof AppProcessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revisions': {
      id: '/_app/revisions'
      path: '/revisions'
      fullPath: '/revisions'
      preLoaderRoute: typeof AppRevisionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBoqRoute: typeof AppBoqRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFindingsRoute: typeof AppFindingsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNewAuditRoute: typeof AppNewAuditRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProcessingRoute: typeof AppProcessingRoute
  AppReportRoute: typeof AppReportRoute
  AppResultsRoute: typeof AppResultsRoute
  AppRevisionsRoute: typeof AppRevisionsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoqRoute: AppBoqRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFindingsRoute: AppFindingsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNewAuditRoute: AppNewAuditRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProcessingRoute: AppProcessingRoute,
  AppReportRoute: AppReportRoute,
  AppResultsRoute: AppResultsRoute,
  AppRevisionsRoute: AppRevisionsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
